name: Run-checkmycode

on:
  workflow_call:
    secrets:
      ORG_NPM_INSTALL:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout github repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: setup-latest-npm
        run: npm install -g npm@latest

      - name: permissions
        run: |
           git config --global user.name=AcademixPro
           git config --global user.email=academixpro0@gmail.com
           git config --global user.pssword=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
          
      - name: getdependencies
        run: npm ci

      - name: checkmycode
        run: bash checkmycode.sh
